### ISSUE TITLE
default user name and password

### ISSUE THREAD

**Issue by ray-rahul** [IHTSDO/component-identifier-service#11]
Can anybody help with the default user id and password for component-identifier-service login screen ? Where is the user created additionally ?

**Comment by kaicode** [comment]
Hi @ray-rahul 
The CIS authenticates using Atlasian Crowd so there is no default user id and password.
You could either install Crowd or modify the security module to suit your needs. The relevant code section is here https://github.com/IHTSDO/component-identifier-service/blob/master/blogic/Security.js
Kind regards, Kai
