### ISSUE TITLE
config/db_script.sql should use ENGINE=InnoDB instead of ENGINE=MyISAM

### ISSUE THREAD

**Issue by jschneid-nmdp** [IHTSDO/component-identifier-service#19]
The config/db_script.sql database creation script uses ENGINE=MyISAM for most of its tables.

Recommended change -- revise CREATE TABLE statements to use ENGINE=InnoDB instead of ENGINE=MyISAM.

**Comment by kaicode** [comment]
Hi @jschneid-nmdp 
Thank you for your suggestion. Could you give a little more information to support your suggestion please?
Kind regards, Kai
