### ISSUE TITLE
Component Identifier Service - Admin tool Access

### ISSUE THREAD

**Issue by Kartik-Rai** [IHTSDO/component-identifier-service#21]
Hi Kai,

Greetings for the day!
From where I can find the Admin tool (https://localhost/admin) credentials, or if the service has any default password? 
Kindly do the needful.

Thanks & Regards
Kartik Rai
NRCeS India

**Comment by kaicode** [comment]
Hi there,

This tool uses Atlassian Crowd for authentication and authorisation. I am not aware of a default username and password. The user must be created within Crowd and be part of the right user group to have permission to access the tool. 
The crowd user groups are `component-identifier-service-user` and `component-identifier-service-admin`.

Feel free to fork the repository and change the authentication mechanism for your needs.

Kind regards,
Kai
